#!/usr/bin/env python3

import boto3
from flask import g, session
from redis import Redis
from flask_bcrypt import Bcrypt

from src.app import app
import config

from sys import argv

# set up flask app
app.secret_key = config.secret_key

# TODO this should somehow be elsewhere
@app.before_request
def bucket_factory():
    g.s3 = boto3.resource('s3', **config.s3)
    g.client = boto3.client('s3', **config.s3)
    g.bucket = g.s3.Bucket(config.bucket_name)

@app.before_request
def redis_factory():
    g.redis = Redis(config.redis)

@app.before_request
def bcrypt_factory():
    g.bcrypt = Bcrypt(app)

app.run(debug='--debug' in argv[1:])
