#!/usr/bin/env python3

import boto3
from flask import g, session

from src.app import app
import config

from sys import argv

# set up flask app
app.secret_key = config.secret_key

def is_authenticated():
    return session.get('t') == config.valid_token

# TODO this should somehow be elsewhere
@app.before_request
def bucket_factory():
    g.s3 = boto3.resource('s3', **config.s3)
    g.client = boto3.client('s3', **config.s3)
    g.bucket = g.s3.Bucket(config.bucket_name)

    # FIXME actually check credentials
    g.is_authenticated = is_authenticated

app.run(debug='--debug' in argv[1:])
