"""empty message

Revision ID: eda5a9aaf951
Revises: 
Create Date: 2020-04-15 22:53:54.356086

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'eda5a9aaf951'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=False),
    sa.Column('phash', sa.Binary(), nullable=False),
    sa.Column('last_login_on', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('invitation',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('consumer_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation')
    op.drop_table('user')
    # ### end Alembic commands ###
